name: Publish JAR to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew build

      - name: Clone GitHub Pages repository
        run: |
          git clone --depth 1 https://github.com/sandro642/sandro642.github.io.git gh-pages
          cd gh-pages
          git checkout main

      - name: Copy JAR to connectorapi/jar
        run: |
          rm -rf gh-pages/connectorapi/jar/*
          mkdir -p gh-pages/connectorapi/jar
          cp build/libs/*.jar gh-pages/connectorapi/jar/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add connectorapi/jar
          git commit -m "Update JAR for connectorapi" || echo "No changes to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/sandro642/sandro642.github.io.git main
