name: Publish Javadoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Clone GitHub Pages repository
        run: |
          git clone --depth 1 https://github.com/sandro642/sandro642.github.io.git gh-pages
          cd gh-pages
          git checkout main

      - name: Copy Javadoc to connectorapi/javadoc
        run: |
          rm -rf gh-pages/connectorapi/javadoc/*
          mkdir -p gh-pages/connectorapi/javadoc
          cp -r build/docs/javadoc/* gh-pages/connectorapi/javadoc/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add connectorapi/javadoc
          git commit -m "Update Javadoc for connectorapi" || echo "No changes to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/sandro642/sandro642.github.io.git main
