name: Publish JAR to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish Maven artifacts to local repo
        run: ./gradlew publish
        env:
          GROUP_ID: fr.sandro642.github
          ARTIFACT_ID: ConnectorAPI
          VERSION: 0.1.0

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository-name: sandro642/sandro642.github.io
          branch: main
          folder: build/repo
          target-folder: connectorapi/jar
